Add Makefile
IEEE-VIT/termiboard pull request #41
Opened 2020-10-03 11:48 UTC by MistaTwista

Makefile help newcomers to understand what to do with project.

By running:
```bash
$ make help
```
or just
```bash
$ make
```
there will be help message with all available commands.

Help message parsed from Makefile itself, by finding
`##` comments after command name.

Currently usefull commands are:
- *dep* - install dependencies and make vendoring folder
- *test*- run unit tests, but before it runs `dep`
- *build* - run test and build a binary into ./bin folder
- *run* - just execute binary
- *rerun* - build and run
- *printvars* - print all variables available for make
its usefull when you need to debug some settings

On top of Makefile there are variables for all these commands, like:
- PROJECT_NAME
- BUILD_DIR
- VERSION
- BUILD_DATE
- COMMIT_SHA
- and LDFLAGS

LDFLAGS used on binary compilation, to inject some build data
and get this information inside app.

Also this commit contains small changes in forming of version string

There is a good practices to add version with git tags, but also
a commit message and build date.

2020-10-03 21:04 UTC, aryan9600 requested changes
Can we also have a target `clean` which runs `go clean`?

2020-10-03 21:04 UTC, aryan9600 commented on Makefile
> +BUILD_DIR = bin
I think it'll be better to have the BUILD_DIR as the root of the project itself.

2020-10-04 17:17 UTC, MistaTwista commented on Makefile
> +BUILD_DIR = bin
I think it's easier to .gitignore folder with some files than just some files in the root of a project, perhaps in future you will generate several binaries for different operating systems, so you will need to add them in .gitignore or don't think about it, and just put `bin` folder there.

2020-10-04 17:37 UTC, MistaTwista commented on Makefile
> +BUILD_DIR = bin
also, there is something like standard layout for go projects, you can read about it [here](https://medium.com/@benbjohnson/structuring-applications-in-go-3b04be4ff091) and [there](https://github.com/golang-standards/project-layout)

2020-10-04 17:57 UTC, MistaTwista commented
Added `make clean` command

2020-10-04 21:11 UTC, aryan9600 commented on Makefile
> +BUILD_DIR = bin
Actually termiboard aims to ship one binary for all platforms, but after going through the articles (thanks for the links btw), I think it makes sense to have it a `/bin` folder. 👍

2020-10-06 05:28 UTC, aryan9600 approved these changes
LGTM!

2020-10-06 05:28 UTC, merged